Repository StockmonGo/FE-stockmon, pull requests merged in 2024-09, with the labels that each got.

#61 [Feat] 스톡몬 계란판 UI 구현 #17
  dummy/books/bookDetail.json
  dummy/books/books.json
  src/app/animations.css
  src/app/books/[id]/collection/layout.tsx
  src/app/books/[id]/collection/page.tsx
  src/app/books/[id]/layout.tsx
  src/components/ui/Modal.tsx
  src/components/ui/NewPoint.tsx
  src/components/ui/books/CountHeader.tsx
  src/components/ui/books/RealStockExchangeModal.tsx
  src/components/ui/books/StockmonCard.tsx
  src/components/ui/books/StockmonItem.tsx
  src/components/ui/books/StockmonList.tsx
  src/types/stockmons.ts
Labels: ✨ feature

#65 [Feat] 검색바 필터링 구현 #62
  src/app/books/[id]/page.tsx
  src/app/books/page.tsx
  src/components/ui/SearchBar.tsx
  src/components/ui/books/RealStockExchangeModal.tsx
  src/components/ui/books/StockmonList.tsx
Labels: ✨ feature

#73 [Feat] 도감에서 스톡몬 목록 가져오는 api연결 및 api 리팩토링 #70
  src/apis/baseAPI.ts
  src/apis/stockBookAPI.ts
  src/app/books/page.tsx
  src/components/ui/books/StockmonCard.tsx
  src/components/ui/books/StockmonItem.tsx
  src/components/ui/books/StockmonList.tsx
  src/components/ui/books/StockmonStock.tsx
  src/lib/utils.ts
  src/types/ApiResponse.ts
  src/types/ErrorResponse.ts
  src/types/SuccessResponse.ts
  src/types/stockmons.ts
Labels: ✨ feature

#74 [FEAT] 멤버 계좌 관련 API 추가 #67
  src/apis/memberAPI.ts
  src/app/profile/page.tsx
  src/components/ui/Loading.tsx
  src/components/ui/profile/UserMenu.tsx
  src/types/member.ts
Labels: ✨ feature

#79 [Feat] 스톡몬 상세 조회 api 연결 및 차트 UI 구현 #75
  package-lock.json
  package.json
  src/apis/baseAPI.ts
  src/apis/stockBookAPI.ts
  src/app/books/[id]/page.tsx
  src/app/books/page.tsx
  src/components/ui/books/StockmonChart.tsx
  src/components/ui/books/TradingViewWidget.tsx
  src/hooks/useStockBook.ts
  src/types/stockmons.ts
Labels: ✨ feature

#85 [Feat] 스톡몬 계란판 페이지 API 연동 #83
  src/apis/stockBookAPI.ts
  src/app/books/[id]/collection/page.tsx
  src/components/ui/books/StockmonCard.tsx
  src/components/ui/books/StockmonItem.tsx
  src/hooks/useStockBook.ts
Labels: ✨ feature

#86 [FEAT] 주변 정보 API, 스톡타워 관련 API 추가 #59
  public/images/peachTower.svg
  src/apis/mapAPI.ts
  src/apis/memberAPI.ts
  src/app/world/page.tsx
  src/components/ui/world/StockTowerModal.tsx
  src/store/store.ts
  src/types/location.ts
Labels: ✨ feature

#94 [FEAT] 스톡볼 조회, 마당 조회, pwa 추가 #88
  .gitignore
  next.config.js
  next.config.mjs
  package.json
  public/icons/templogo.png
  public/images/logo-192x192.png
  public/images/logo-48x48.png
  public/images/logo-512x512.png
  public/images/logo-96x96.png
  public/manifest.json
  src/apis/mapAPI.ts
  src/app/layout.tsx
  src/app/world/page.tsx
  src/app/yard/page.tsx
  src/components/ui/profile/UserProfile.tsx
  src/components/ui/world/StockTowerModal.tsx
  src/components/ui/world/TopNavBar.tsx
  src/components/ui/yard/StockmonFeel.tsx
  src/types/location.ts
Labels: ✨ feature

#97 [Feat] 현재 주가 실시간으로 받아오는 소켓 연결 완료 #66
  package-lock.json
  package.json
  public/sw.js
  public/workbox-4754cb34.js
  src/app/books/[id]/collection/page.tsx
  src/app/books/[id]/page.tsx
  src/components/ui/books/StockmonCard.tsx
  src/components/ui/books/StockmonStock.tsx
  src/sockets/baseStomp.ts
Labels: ✨ feature

#102 [Design] 로딩 화면, 토스트, 기타 예외처리 화면 css 추가 #87
  .gitignore
  package-lock.json
  package.json
  src/apis/baseAPI.ts
  src/app/[...404]/page.tsx
  src/app/books/[id]/collection/page.tsx
  src/app/books/page.tsx
  src/app/dev/ui/page.tsx
  src/components/ui/Error.tsx
  src/components/ui/Loading.tsx
  src/components/ui/books/StockmonCard.tsx
  src/components/ui/books/StockmonItem.tsx
  src/hooks/useToast.tsx
Labels: :art: design

#105 [FEAT] 맵 관련 세부사항, 로그인 확인 추가 #95
  package.json
  src/app/world/page.tsx
  src/components/BeforeInstallPrompt.tsx
  src/components/MobileInstallPrompt.tsx
  src/components/ui/world/StockTowerModal.tsx
  src/hooks/useAuth.ts
  src/middleware.ts
  src/types/window.ts
Labels: ✨ feature

#107 [Feat] 스톡몬 교환 API 연동 #103
  src/app/alliances/page.tsx
  src/app/books/[id]/page.tsx
  src/app/game/new-stockmon/page.tsx
  src/app/world/page.tsx
  src/components/ui/Modal.tsx
  src/components/ui/books/StockmonExchangeModal.tsx
  src/components/ui/message/StockExchangeModal.tsx
  src/hooks/useAlliance.ts
  src/hooks/useExchange.ts
Labels: ✨ feature

#111 [Feat] 스톡몬 상세 페이지 chart api 연동 #108
  src/apis/stockBookAPI.ts
  src/app/books/[id]/page.tsx
  src/components/ui/books/StockmonChart.tsx
  src/types/stockmons.ts
Labels: ✨ feature

#113 [FEAT] 월드 로그인 안 한 유저 처리 #109
  src/app/world/page.tsx
Labels: ✨ feature

#114 [Feat] 실시간 현재 주가 받아오기 및 차트 반영 #112
  src/components/ui/books/StockmonChart.tsx
  src/components/ui/books/StockmonStock.tsx
  src/components/ui/message/StockExchangeModal.tsx
  src/store/store.ts
  src/types/stockmons.ts
  src/types/stocks.ts
Labels: ✨ feature

#118 [Design] 애니메이션 및 css 수정 #115
  package.json
  src/app/animations.css
  src/app/books/page.tsx
  src/app/dev/ui/page.tsx
  src/app/world/page.tsx
  src/components/game/Confetti.tsx
  src/components/game/NewStockmon.tsx
  src/components/game/TimingGame.tsx
  src/components/ui/Skeleton.tsx
  src/components/ui/books/StockmonCard.tsx
  src/components/ui/world/LoadingMap.tsx
  src/components/ui/world/loading-map.css
  src/hooks/useVibrate.ts
Labels: :art: design

#121 [FEAT] 튜토리얼 추가 및 월드 액세스 토큰 관련 변경 #110
  package.json
  public/images/tutorial1.svg
  public/images/tutorial2.svg
  public/images/tutorial3.svg
  public/images/tutorial4.svg
  public/images/tutorial5.svg
  src/apis/memberAPI.ts
  src/app/layout.tsx
  src/app/tutorial/page.tsx
  src/app/users/login/page.tsx
  src/app/users/register/page.tsx
  src/app/world/page.tsx
  src/types/member.ts
  src/utils/screen.ts
Labels: ✨ feature

#130 [Feat] 버그 수정 및 css 수정 #123
  src/app/animations.css
  src/app/books/[id]/collection/page.tsx
  src/app/books/[id]/layout.tsx
  src/app/books/[id]/page.tsx
  src/app/game/new-stockmon/page.tsx
  src/app/world/page.tsx
  src/components/game/NewStockmonInfo.tsx
  src/components/game/TimingGame.tsx
  src/components/ui/SimpleLoading.tsx
  src/components/ui/books/StockTag.tsx
  src/components/ui/books/StockmonCard.tsx
Labels: 🐛 fix

#132 [Fix] 복숭아 없는 경우 토스트 및 빵빠레 시간 조절
  src/components/game/Confetti.tsx
  src/components/game/TimingGame.tsx
Labels: 🐛 fix

#136 [FIX] 화면 크기 및 사파리 h-fit 수정
  src/app/tutorial/page.tsx
  src/app/users/layout.tsx
  src/app/world/layout.tsx
  src/app/world/page.tsx
  src/app/yard/page.tsx
  src/components/BeforeInstallPrompt.tsx
  src/components/MobileInstallPrompt.tsx
Labels: 🐛 fix

#139 [DESIGN] 파비콘과 제목 변경 #137
  src/app/favicon.ico
  src/app/layout.tsx
Labels: :art: design

#141 [Feat] 교환창에 개수 보이도록 수정 및 다 css 수정 #134
  src/app/alliances/layout.tsx
  src/app/alliances/page.tsx
  src/app/game/new-stockmon/page.tsx
  src/app/game/page.tsx
  src/app/message/layout.tsx
  src/app/message/page.tsx
  src/app/profile/page.tsx
  src/components/game/NewStockmonInfo.tsx
  src/components/ui/Button.tsx
  src/components/ui/Error.tsx
  src/components/ui/Loading.tsx
  src/components/ui/Modal.tsx
  src/components/ui/books/StockmonCard.tsx
  src/components/ui/books/StockmonStock.tsx
  src/components/ui/message/StockExchangeModal.tsx
  src/components/ui/profile/UserMenu.tsx
Labels: ✨ feature

#145 [FIX] 마당 스톡목 빈배열일 때 처리 #140
  src/app/yard/page.tsx
Labels: :art: design
