Repository StockmonGo/FE-stockmon, pull requests merged in 2024-08, with the labels that each got.

#6 feat: 도감, 스톡몬 상세, 스톡몬 모으는 페이지 생성하고 연결
  src/app/books/[id]/collection/page.tsx
  src/app/books/[id]/page.tsx
  src/app/books/page.tsx
Labels: ✨ Feature

#8 Origin/feat modal #7
  .vscode/settings.json
  public/icons/button-close.svg
  public/icons/button-ok-off.svg
  public/icons/button-ok-on.svg
  src/app/dev/ui/page.tsx
  src/components/ui/Button.tsx
  src/components/ui/Modal.tsx
Labels: ✨ feature

#15 [Feat] 도감 첫페이지 생성 #9
  .vscode/settings.json
  components.json
  package-lock.json
  package.json
  public/icons/CloseButton.svg
  public/icons/button-close.svg
  public/icons/button-ok-off.svg
  public/icons/button-ok-on.svg
  public/images/bg.jpg
  public/images/octopus.png
  src/app/books/layout.tsx
  src/app/books/page.tsx
  src/app/dev/game/style.scss
  src/app/dev/layout.tsx
  src/app/dev/layout/layout.tsx
  src/app/dev/layout/page.tsx
  src/app/dev/ui/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/ui/BtnClose.tsx
  src/components/ui/Button.tsx
  src/components/ui/CommonLayout.tsx
  src/components/ui/Modal.tsx
  src/components/ui/SearchBar.tsx
  src/components/ui/Skeleton.tsx
  src/components/ui/books/CountHeader.tsx
  src/components/ui/books/StockmonItem.tsx
  src/components/ui/books/StockmonList.tsx
  src/lib/utils.ts
  src/types/books/StockmonType.ts
  tailwind.config.ts
Labels: ✨ feature

#19 [Feat] 도감 첫페이지 UI 완성 #2
  components.json
  package-lock.json
  package.json
  public/images/octopus.png
  src/app/books/[id]/collection/page.tsx
  src/app/books/[id]/page.tsx
  src/app/books/layout.tsx
  src/app/books/page.tsx
  src/app/globals.css
  src/components/ui/CommonLayout.tsx
  src/components/ui/SearchBar.tsx
  src/components/ui/Skeleton.tsx
  src/components/ui/books/CountHeader.tsx
  src/components/ui/books/StockmonItem.tsx
  src/components/ui/books/StockmonList.tsx
  src/lib/utils.ts
  src/types/books/StockmonType.ts
  tailwind.config.ts
Labels: ✨ feature

#23 [Refactor] 더미 데이터는 소스와 별도 폴더로 추출 #2
  dummy/books/books.json
  src/app/books/page.tsx
Labels: :recycle: refactor

#40 [Feat] 도감에서 스톡몬 상세 페이지 상단 카드 부분 UI 구현 #29
  dummy/books/bookDetail.json
  dummy/books/books.json
  public/images/bgStamp.svg
  public/images/ribbon.png
  src/app/animations.css
  src/app/books/[id]/collection/page.tsx
  src/app/books/[id]/layout.tsx
  src/app/books/[id]/page.tsx
  src/components/ui/books/StockmonCard.tsx
  src/components/ui/books/StockmonItem.tsx
  src/components/ui/books/StockmonList.tsx
  src/types/books/StockmonType.ts
  src/types/stockmons.ts
Labels: ✨ feature

#46 [FEAT] 마당 페이지 UI
  public/icons/depress-feeling.svg
  public/images/dummy-stockmon1.png
  public/images/dummy-stockmon2.png
  public/images/yardBg.png
  src/app/yard/page.tsx
  src/components/ui/yard/StockmonFeel.tsx
Labels: ✨ feature

#48 [Feat] 스톡몬 주가 정보 UI 구현 #30
  dummy/alliance/alliances.json
  dummy/alliance/searchTraveler.json
  dummy/books/bookDetail.json
  package.json
  public/icons/add-alliance.svg
  public/icons/delete-alliance.svg
  public/icons/depress-feeling.svg
  public/icons/exchange-alliance.svg
  public/images/cannot-find.png
  public/images/dummy-stockmon1.png
  public/images/dummy-stockmon2.png
  public/images/logo-160x160.png
  public/images/logo-280x280.png
  public/images/stockBubbleBottom.png
  public/images/stockBubbleTop.png
  public/images/yardBg.png
  src/app/account/layout.tsx
  src/app/account/login/page.tsx
  src/app/account/page.tsx
  src/app/account/register/page.tsx
  src/app/alliance/layout.tsx
  src/app/alliance/page.tsx
  src/app/books/[id]/page.tsx
  src/app/books/books.css
  src/app/globals.css
  src/app/message/page.tsx
  src/app/profile/page.tsx
  src/app/users/layout.tsx
  src/app/users/login/page.tsx
  src/app/users/page.tsx
  src/app/users/register/page.tsx
  src/app/yard/page.tsx
  src/components/ui/Modal.tsx
  src/components/ui/SearchBar.tsx
  src/components/ui/alliance/AllianceItem.tsx
  src/components/ui/books/Row.tsx
  src/components/ui/books/StockTag.tsx
  src/components/ui/books/StockmonCard.tsx
  src/components/ui/books/StockmonStock.tsx
  src/components/ui/message/MessageItem.tsx
  src/components/ui/message/StockExchangeModal.tsx
  src/components/ui/profile/UserMenu.tsx
  src/components/ui/profile/UserProfile.tsx
  src/components/ui/yard/StockmonFeel.tsx
  src/types/stockmons.ts
  src/types/stocks.ts
  tailwind.config.ts
Labels: ✨ feature

#49 [Feat] 도감 상세 페이지의 스톡몬 카드, 주가 정보 컴포넌트 구현 #16
  dummy/books/bookDetail.json
  dummy/books/books.json
  public/images/bgStamp.svg
  public/images/ribbon.png
  public/images/stockBubbleBottom.png
  public/images/stockBubbleTop.png
  src/app/animations.css
  src/app/books/[id]/collection/page.tsx
  src/app/books/[id]/layout.tsx
  src/app/books/[id]/page.tsx
  src/app/books/books.css
  src/app/books/page.tsx
  src/components/ui/Error.tsx
  src/components/ui/Loading.tsx
  src/components/ui/books/Row.tsx
  src/components/ui/books/StockTag.tsx
  src/components/ui/books/StockmonCard.tsx
  src/components/ui/books/StockmonChart.tsx
  src/components/ui/books/StockmonItem.tsx
  src/components/ui/books/StockmonList.tsx
  src/components/ui/books/StockmonStock.tsx
  src/types/books/StockmonType.ts
  src/types/stockmons.ts
  src/types/stocks.ts
  tailwind.config.ts
Labels: ✨ feature

#52 [Feat] 스톡몬 상세 페이지 차트 배경 UI 구현 #51
  public/images/chartWave.svg
  src/app/animations.css
  src/app/books/[id]/layout.tsx
  src/components/ui/books/StockmonChart.tsx
Labels: ✨ feature
